name: Atualizar CSV

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # 🔥 ESSENCIAL

    steps:
      - name: Baixar repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script
        run: python script.py

      - name: Commit CSV
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add dados.csv
          git commit -m "update csv" || echo "sem mudanças"
          git push
